# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webforum.az.api:
    image: ${APP_CREATED_IMAGE}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ASPNET_ENVIRONMENT}
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__DefaultConnection=${DatabaseConnectionString}
      - RedisOptions__ConnectionString=${CacheConnectionString}
      - MassTransit__PublishEnabled=${MassTransitPublishEnabled}
      - MassTransit__RabbitMq__Uri=${RabbitUri}
      - ThreadPool__MinimumThreads=${ThreadPoolMinimumThreads}
      - AuthorityOptions__Authority=${Authority}
      - AuthorityOptions__Realm=${Realm}
      - AuthorityOptions__Resource__Name=${ResourceName}
      - AuthorityOptions__Resource__SslRequired=${ResourceSslRequired}
      - AuthorityOptions__Resource__PublicClient=${ResourcePublicClient}
      - AuthorityOptions__Resource__ConfidentialPort=${ResourceConfidentialPort}
      - AuthorityOptions__Swagger__Scope=${SwaggerScope} 
    networks:
      - ${APP_NETWORK}
    restart: always

networks:
  fb-core-shared:
    external:
      name: ${APP_NETWORK}
      